### PR TITLE
Fixes #12590: removed chef_ssl_pem_file parameter from default_settings list

### PR DESCRIPTION
**Pull request by witlessbird**

### CODE REVIEW

**Comment by ares** [comment]
I don't follow, `chef_ssl_pem_file` is [used](https://github.com/theforeman/smart_proxy_chef/blob/548706a38384887ef0d7a35884e89364580e90e4/lib/smart_proxy_chef_plugin/connection_helper.rb#L12)

**Comment by witlessbird** [comment]
Oops, apologies, don't know how I missed that. Nods, no need to initialize settings with nils -- you get back nil for any key that isn't present. 

This change is still needed (I'll update the commit message) -- any setting listed in 'default_settings' is now treated as a required one (as in having a non-nil value), smart_proxy_chef plugin will fail to load without it.

**Comment by witlessbird** [comment]
@ares: updated the commit message.

**Comment by ares** [comment]
Tested, works fine, thank you and sorry for the delay.

**Comment by ares** [comment]
Merged as cc96dc3d783f223e1d8ba970bb1609232aa9e6d3

**Pull request closed without merging**
