### PR TITLE
Fixes #10818: part-1 -- moved Reports and Facts classes to smart_proxy_chef

### PR DESCRIPTION
**Pull request by witlessbird**

### CODE REVIEW

**Comment by ares** [comment]
OOC wasn't this used by salt as well? In what version of smart proxy will this be removed?

**Comment by witlessbird** [comment]
I don't see either of the classes being used by the salt plugin. Could you check just to make sure? I was going to wait until this PR has been accepted before removing the classes from the smart-proxy. Another small change will be required to smart_proxy_chef after that -- I'd like to pin the minimum smart-proxy version in https://github.com/theforeman/smart_proxy_chef/blob/master/lib/smart_proxy_chef_plugin/chef_plugin.rb

**Comment by ares** [comment]
Right, I don't see it in salt either, maybe they upload these data directly? Ok, I'll try to find some time to test and merge this week. I suppose I'll have to do a new release when you remove it from smart-proxy develop. Thanks for the PR btw!

**Comment by ares** [comment]
With this patch, proxy does not start since it can't find various files and constants. I think I've fixed all problems in https://gist.github.com/ares/ff1608255276378d8014, @witlessbird could you review and incorporate in you PR please? Tested with this and it uploads reports and facts fine even when I delete both classes from smart proxy.

**Comment by witlessbird** [comment]
thanks for catching this, I tested with an old version of smart-proxy that had those requests in place, and therefore everything worked when it shouldn't. fixed now.

**Comment by ares** [comment]
great, thanks @witlessbird, I reworded a commit message a bit and merged as 7b4bd15bbdf6e407156c62fb31ce84ba98db5a1d

**Pull request closed without merging**
